### ISSUE TITLE
suggest for github action

### ISSUE THREAD

**Issue by Ran-Xing** [blacktop/docker-zeek#26]
# update readme to hub.docker.com
```yaml
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: blacktop/docker-zeek
```
